"""InvenioRDM settings for Helix project.

This file was automatically generated by 'invenio-cli init'.

For the full list of settings and their values, see
https://inveniordm.docs.cern.ch/reference/configuration/.
"""

import os
from datetime import datetime

from invenio_app_rdm.config import (
    VOCABULARIES_DATASTREAM_READERS,
    VOCABULARIES_DATASTREAM_WRITERS,
)
from invenio_notifications.backends.email import EmailNotificationBackend
from invenio_oauthclient.views.client import auto_redirect_login
from invenio_rdm_records.config import RDM_PERSISTENT_IDENTIFIERS
from invenio_rdm_records.services.components import DefaultRecordsComponents

from ..datastreams import AffiliationsWriter, StreamingYamlSequenceReader
from ..imperial_schema import ImperialRecordSchema
from ..permissions import ImperialRecordPermissionPolicy
from ..service_components import SymplecticComponent
from .custom_fields import *  # noqa: F401,F403
from .utils import get_user_form_default

# Flask
# =====
# See https://flask.palletsprojects.com/en/1.1.x/config/

# Define the value of the cache control header `max-age` returned by the server when
# serving public files. Files will be cached by the browser for the provided number of
# seconds.  See flask documentation for more information:
# https://flask.palletsprojects.com/en/2.1.x/config/#SEND_FILE_MAX_AGE_DEFAULT
SEND_FILE_MAX_AGE_DEFAULT = 300

# SECURITY WARNING: keep the secret key used in production secret!
# Do not commit it to a source code repository.
SECRET_KEY = "CHANGE_ME"

TRUSTED_HOSTS = ["0.0.0.0", "localhost", "127.0.0.1"]

# Flask-SQLAlchemy
# ================
# See https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/

SQLALCHEMY_DATABASE_URI = (
    "postgresql+psycopg2://ic-data-repo:ic-data-repo@localhost/ic-data-repo"
)


# Invenio-App
# ===========
# See https://invenio-app.readthedocs.io/en/latest/configuration.html

APP_DEFAULT_SECURE_HEADERS = {
    "content_security_policy": {
        "default-src": [
            "'self'",
            "data:",  # for fonts
            "'unsafe-inline'",  # for inline scripts and styles
            "blob:",  # for pdf preview
            # Add your own policies here (e.g. analytics)
        ],
    },
    "content_security_policy_report_only": False,
    "content_security_policy_report_uri": None,
    "force_file_save": False,
    "force_https": True,
    "force_https_permanent": False,
    "frame_options": "sameorigin",
    "frame_options_allow_from": None,
    "session_cookie_http_only": True,
    "session_cookie_secure": True,
    "strict_transport_security": True,
    "strict_transport_security_include_subdomains": True,
    "strict_transport_security_max_age": 31556926,  # One year in seconds
    "strict_transport_security_preload": False,
}


# Invenio-Theme
# =============
# See https://invenio-theme.readthedocs.io/en/latest/configuration.html

THEME_FRONTPAGE_SUBTITLE = "Imperial College London's FAIR Data Repository"
THEME_FRONTPAGE_TITLE = "Helix"
# Header logo
THEME_LOGO = "images/imperial_logo_blue.svg"
INVERTED_THEME_LOGO = "images/imperial_white_blue.svg"


# Invenio-App-RDM
# ===============
# See https://invenio-app-rdm.readthedocs.io/en/latest/configuration.html

# Instance's theme entrypoint file. Path relative to the ``assets/`` folder.
INSTANCE_THEME_FILE = "./less/theme.less"


# Invenio-Records-Resources
# =========================
# See:
# https://github.com/inveniosoftware/invenio-records-resources/blob/master/invenio_records_resources/config.py

SITE_UI_URL = "https://127.0.0.1"

SITE_API_URL = "https://127.0.0.1/api"

APP_RDM_DEPOSIT_FORM_DEFAULTS = {
    "resource_type": "dataset",
    "publication_date": lambda: datetime.now().strftime("%Y-%m-%d"),
    "rights": [
        {
            "id": "cc-by-4.0",
            "title": "Creative Commons Attribution 4.0 International",
            "description": (
                "The Creative Commons Attribution license allows "
                "re-distribution and re-use of a licensed work "
                "on the condition that the creator is "
                "appropriately credited."
            ),
            "link": "https://creativecommons.org/licenses/by/4.0/legalcode",
        }
    ],
    "publisher": "Imperial College London",
    "creators": lambda: get_user_form_default(),
}

# Override record schemas
RDM_RECORD_SCHEMA = ImperialRecordSchema

# See:
# https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/config.py
APP_RDM_DEPOSIT_FORM_AUTOCOMPLETE_NAMES = "search"  # "search_only" or "off"

# Invenio-RDM-Records
# ===================
# See https://inveniordm.docs.cern.ch/customize/dois/
DATACITE_ENABLED = False
DATACITE_USERNAME = ""
DATACITE_PASSWORD = ""
DATACITE_PREFIX = ""
DATACITE_TEST_MODE = True
DATACITE_DATACENTER_SYMBOL = ""

# Remove "external" as a DOI provider
RDM_PERSISTENT_IDENTIFIERS["doi"]["providers"].remove("external")

# Authentication - Invenio-Accounts and Invenio-OAuthclient
# =========================================================
# See: https://inveniordm.docs.cern.ch/customize/authentication/

# Invenio-Accounts
# ----------------
# See:
# https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/config.py
ACCOUNTS_LOCAL_LOGIN_ENABLED = True  # enable local login
SECURITY_REGISTERABLE = False  # local login: allow users to register
SECURITY_RECOVERABLE = False  # local login: allow users to reset the password
SECURITY_CHANGEABLE = False  # local login: allow users to change psw
SECURITY_CONFIRMABLE = True  # local login: users can confirm e-mail address
SECURITY_LOGIN_WITHOUT_CONFIRMATION = (
    False  # require users to confirm email before being able to login
)
SECURITY_LOGIN_USER_TEMPLATE = "invenio_accounts/login_user.html"

# Invenio-OAuthclient
# -------------------
# See:
# https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/config.py

OAUTHCLIENT_REMOTE_APPS = dict()

ICL_OAUTH_CLIENT_ID = os.getenv("ICL_OAUTH_CLIENT_ID")
ICL_OAUTH_CLIENT_SECRET = os.getenv("ICL_OAUTH_CLIENT_SECRET")
ICL_OAUTH_WELL_KNOWN_URL = "https://login.microsoftonline.com/2b897507-ee8c-4575-830b-4f8267c3d307/v2.0/.well-known/openid-configuration"  # noqa: E501
ICL_MICROSOFT_TENANT_ID = "2b897507-ee8c-4575-830b-4f8267c3d307"

ICL_GRAPH_API_ENABLED = ICL_OAUTH_CLIENT_ID and ICL_OAUTH_CLIENT_SECRET

if ICL_GRAPH_API_ENABLED:
    OAUTHCLIENT_REMOTE_APPS["icl"] = dict(
        title="Imperial College Single Sign On",
        description="Authentication via membership of Imperial College",
        icon="",
        params=dict(
            request_token_params=dict(scope="openid profile"),
            base_url="",
            request_token_url=None,
            access_token_url="https://login.microsoftonline.com/2b897507-ee8c-4575-830b-4f8267c3d307/oauth2/v2.0/token",  # noqa: E501
            access_token_method="POST",
            authorize_url="https://login.microsoftonline.com/2b897507-ee8c-4575-830b-4f8267c3d307/oauth2/v2.0/authorize",  # noqa: E501
            app_key="ICL_APP_CREDENTIALS",
        ),
        authorized_handler="invenio_oauthclient.handlers:authorized_signup_handler",
        disconnect_handler="invenio_oauthclient.handlers:disconnect_handler",
        signup_handler=dict(
            info="ic_data_repo.auth.oauth:info_handler",
        ),
        signup_options=dict(auto_confirm=True, send_register_msg=False),
    )
    ICL_APP_CREDENTIALS = {
        "consumer_key": ICL_OAUTH_CLIENT_ID,
        "consumer_secret": ICL_OAUTH_CLIENT_SECRET,
    }

ACCOUNTS_LOGIN_VIEW_FUNCTION = (
    auto_redirect_login  # autoredirect to external login if enabled
)
OAUTHCLIENT_AUTO_REDIRECT_TO_EXTERNAL_LOGIN = False  # autoredirect to external login

# Invenio-UserProfiles
# --------------------
USERPROFILES_READ_ONLY = True

# OAI-PMH
# =======
# See:
# https://github.com/inveniosoftware/invenio-oaiserver/blob/master/invenio_oaiserver/config.py

OAISERVER_ID_PREFIX = "invenio.rcs.ic.ac.uk"
"""The prefix that will be applied to the generated OAI-PMH ids."""

# Invenio-Search
# --------------

SEARCH_INDEX_PREFIX = "ic-data-repo-"

THEME_SHOW_FRONTPAGE_INTRO_SECTION = False

RDM_COMMUNITY_REQUIRED_TO_PUBLISH = True

RDM_ALLOW_METADATA_ONLY_RECORDS = False

NOTIFICATION_BACKENDS = {
    EmailNotificationBackend.id: EmailNotificationBackend,
}

SYMPLECTIC_API_URL = os.getenv("SYMPLECTIC_API_URL")
SYMPLECTIC_API_SUBSCRIPTION_KEY = os.getenv("SYMPLECTIC_API_SUBSCRIPTION_KEY")
SYMPLECTIC_API_AUTH_HEADER = os.getenv("SYMPLECTIC_API_AUTH_HEADER", "Subscription-Key")
SYMPLECTIC_ENABLED = bool(SYMPLECTIC_API_URL and SYMPLECTIC_API_SUBSCRIPTION_KEY)

RDM_PERMISSION_POLICY = ImperialRecordPermissionPolicy

RDM_RECORDS_SERVICE_COMPONENTS = DefaultRecordsComponents + [SymplecticComponent]

VOCABULARIES_DATASTREAM_WRITERS["affiliations-service"] = AffiliationsWriter
VOCABULARIES_DATASTREAM_READERS["stream-yaml"] = StreamingYamlSequenceReader

# Email addresses
# ---------------
SUPPORT_CONTACT_EMAIL = os.getenv("SUPPORT_CONTACT_EMAIL")

USERPROFILES_SETTINGS_TEMPLATE = "ic_data_repo/page_settings.html"
ACCOUNTS_SETTINGS_TEMPLATE = "ic_data_repo/page_settings.html"
OAUTHCLIENT_SETTINGS_TEMPLATE = "ic_data_repo/page_settings.html"

ENABLE_SYPLECTIC_SEARCH = False
APP_RDM_DEPOSIT_FORM_TEMPLATE = "ic_data_repo/deposit.html"
POLICY_DOCUMENTS_URL = "https://www.imperial.ac.uk/research-and-innovation/support-for-staff/scholarly-communication/research-data-management/imperial-policy/"  # noqa: E501
DATA_DEPOSIT_AGREEMENT_URL = "https://www.imperial.ac.uk/research-and-innovation/support-for-staff/scholarly-communication/research-data-management/data-deposit-agreement/"  # noqa: E501


TOTAL_RECORD_STORAGE_LIMIT_BYTES = 10e9
PER_FILE_STORAGE_LIMIT_BYTES = 3.4e9

APP_RDM_DEPOSIT_FORM_QUOTA = {
    "maxStorage": TOTAL_RECORD_STORAGE_LIMIT_BYTES,
    "maxFiles": 100,
}
RDM_FILES_DEFAULT_QUOTA_SIZE = TOTAL_RECORD_STORAGE_LIMIT_BYTES
RDM_FILES_DEFAULT_MAX_FILE_SIZE = PER_FILE_STORAGE_LIMIT_BYTES
FILES_REST_DEFAULT_QUOTA_SIZE = TOTAL_RECORD_STORAGE_LIMIT_BYTES
FILES_REST_DEFAULT_MAX_FILE_SIZE = PER_FILE_STORAGE_LIMIT_BYTES
