site_name: Imperial College London Fair Data Repository

watch: [site/ic_data_repo]

site_dir: docs_site

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
          paths: [.]

nav:
  - Home: index.md
  - Customisation: customisation.md
