[project]
name = "helix"
version = "2026b"
authors = [
    {name = "Imperial College London RSE Team", email = "ict-rse-team@imperial.ac.uk"},
]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
requires-python = "~=3.12.0"
dependencies = [
    "invenio-app-rdm[opensearch2]~=13.0.0",
    "ic-data-repo",
    "lxml",
    "msgraph-sdk",
    "pyuwsgi>=2.0",
    "sqlalchemy-continuum!=1.4.0",
    "types-lxml",
    "types-requests",
    "uwsgi-tools>=1.1.1",
    "uwsgitop>=0.11",
    "setuptools<=81",
]

[dependency-groups]
dev = [
    "mkdocs",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-material",
    "mkdocs-section-index",
    "mkdocstrings-python",
    "pika",
    "pre-commit",
    "pytest-invenio>=4.0.0,<5.0.0",
    # Avoid pytest>=8 as dependency resolution is not giving a compatible version of pluggy
    # Manifests as: https://github.com/pytest-dev/pytest/issues/12144
    "pytest-mypy",
    "pytest<8",
    "selenium",
    "testcontainers",
    "urllib3>=2.6.0", # to avoid CVE-2025-66471
    "webdriver-manager",
]

[tool.uv.sources]
ic-data-repo = {workspace = true}

[tool.uv.workspace]
members = ["site"]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = [
    "D",   # pydocstyle
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "RUF", # ruff
]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
]

[tool.mypy]
disallow_any_generics = true
warn_unreachable = true
warn_unused_ignores = true
exclude = "test_data/.*\\.py"

[[tool.mypy.overrides]]
module = [
       "celery.*",
       "flask_login.*",
       "flask_oauthlib.*",
       "flask_principal.*",
       "ic_data_repo.config.*",
       "ic_data_repo.permissions.*",
       "invenio_access.*",
       "invenio_accounts.*",
       "invenio_app.*",
       "invenio_app_rdm.config.*",
       "invenio_assets.*",
       "invenio_communities.*",
       "invenio_db.*",
       "invenio_i18n.*",
       "invenio_notifications.*",
       "invenio_oauth2server.*",
       "invenio_oauthclient.*",
       "invenio_records_permissions.*",
       "invenio_records_resources.*",
       "invenio_rdm_records.*",
       "invenio_vocabularies.*",
       "marshmallow.*",
       "marshmallow_utils.*",
       "testcontainers.*",
       "flask_resources.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "--mypy --ignore=site/setup.py --ignore-glob=test_data/*.py -m 'not e2e'"
markers = [
    "e2e: End-to-end UI tests",
]
