name: CI
on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
        - "docs/**"
        - "app_data/**"
        - "docker/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pipenv"
      - name: install pipenv and invenio-cli
        run: pip install pipenv invenio-cli
      - name: setup project dependencies
        run: invenio-cli install python
      - name: setup symlink
        run: invenio-cli install symlink
      - name: run tests
        run: pipenv run pytest -p no:warnings
