name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v2.0.3
  test:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pipenv"
      - name: install pipenv and invenio-cli
        run: pip install pipenv invenio-cli
      - name: setup project virtual environment
        run: invenio-cli install
      - name: start services
        run: invenio-cli services start
      - name: run tests
        run: pipenv run pytest
