name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - '!docs/**'
              - '!docker/**'
              - '!.github/**'
              - '**'


  qa:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v2.0.3
  test:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pipenv"
      - name: install pipenv and invenio-cli
        run: pip install pipenv invenio-cli
      - name: setup project dependencies
        run: invenio-cli install python
      - name: setup symlink
        run: invenio-cli install symlink
      - name: start services
        run: invenio-cli services start
      - name: run tests
        run: pipenv run pytest
